### ISSUE TITLE
Enhancement of the navbar 

### ISSUE THREAD

**Issue by acmjec** [acmjec/Hacktober2024-Web_Development--GoHacktober#10]
![image](https://github.com/user-attachments/assets/5623c7b7-def0-4588-9b32-6f7407574454)

**Comment by SlytherSavior** [comment]
Hello! , is this the design to be implemented , or is it the design in the figma file ?  Or is the design to be changed into a completely new one ?

**Comment by ishita2704** [comment]
Hi, I’ve worked on a solution for the navbar issue and created a design to show how we can improve it.

Please check the design here: https://www.figma.com/design/Y13B0UUWNXu5nhIKaMAuDj/Untitled?node-id=0-1&t=jrF84CTn6NP9hPae-1


Please Let me know  if any changes are needed.

![WhatsApp Image 2024-10-19 at 8 40 46 PM](https://github.com/user-attachments/assets/822e99e4-bb37-4d81-b6bf-3ea4ee66662c)

**Comment by ishita2704** [comment]
assign this task to me .

**Comment by chetankhandait** [comment]
Okay @ishita2704  I'm assigning to you

**Comment by ishita2704** [comment]
solved the issue and raised the PR, kindly check.

**Comment by chetankhandait** [comment]
Okay
