### ISSUE TITLE
Add links in the repository section

### ISSUE THREAD

**Issue by acmjec** [acmjec/Hacktober2024-Web_Development--GoHacktober#12]
![image](https://github.com/user-attachments/assets/8e888b08-8781-4f46-ac3c-1f61aa6cd265)

https://github.com/acmjec/Hacktober2024-Web_Development--GoHacktober
https://github.com/acmjec/Hacktoberfest_2024-Android_Plant_Detection
https://github.com/acmjec/CompetitiveCoding_Hacktoberfest2024
https://github.com/acmjec/AI_ML_HacktoberFest_2024

**Comment by devanshjain131** [comment]
Assign this issue.

**Comment by abhiinavjain** [comment]
I have opened a pull request of this issue!
I have added all the respective links.
