### ISSUE TITLE
Add Profile Icon with Dropdown Menu for Dashboard and Profile Page

### ISSUE THREAD

**Issue by acmjec** [acmjec/Hacktober2024-Web_Development--GoHacktober#14]
Description:
Add a profile icon to the navigation bar that includes a dropdown menu. The dropdown should contain links to the following pages:

Dashboard
Profile Page
The profile icon should be visually distinct and easily accessible. Ensure that the dropdown menu is responsive and works well on both desktop and mobile views.

Acceptance Criteria:

Profile icon is added to the navigation bar.
Dropdown menu includes links to the "Dashboard" and "Profile Page."
The design is responsive across different screen sizes.
Links redirect to the appropriate pages.

**Comment by abhiinavjain** [comment]
Please assign this to me!

**Comment by chetankhandait** [comment]
okay assigning  you
