### ISSUE TITLE
Navbar in Repo page has extra Repositories written

### ISSUE THREAD

**Issue by abhiinavjain** [acmjec/Hacktober2024-Web_Development--GoHacktober#25]
![Screenshot 2024-10-20 125421](https://github.com/user-attachments/assets/8389728c-5ed2-49e8-ab9e-c5b1e666b3f1)

**Comment by abhiinavjain** [comment]
Added pull request #23 and corrected this issue

**Comment by chetankhandait** [comment]
> Added pull request #23 and corrected this issue

Lemme chek
